# Generated by Django 4.2 on 2024-04-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField(max_length=200)),
                ('date_arrivée', models.DateTimeField(max_length=200)),
                ('gare_arrivée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gare_arrivée', to='main.gare')),
                ('gare_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gare_depart', to='main.gare')),
            ],
        ),
    ]
