# Generated by Django 4.2 on 2024-04-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reservation_num_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prénom', models.CharField(max_length=200)),
                ('date_de_naissance', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.passager'),
        ),
    ]
